### PR TITLE
fix: implement persistent keep-alive timer to prevent connection timeouts

### LINKED ISSUE #1658: Keep-alive timer destroyed between recv() calls causing connection timeouts
# Keep-Alive Timer Architectural Flaw

## Problem Description

Connections are timing out after 30 seconds even when both peers are actively communicating. The root cause is an architectural flaw in how the keep-alive mechanism is implemented.

## Root Cause Analysis

The keep-alive timer lives inside the `PeerConnection::recv()` function and is destroyed when the function returns:

```rust
// In peer_connection.rs
pub async fn recv(&mut self) -> Result<Vec<u8>> {
    // Keep-alive timer created here
    let mut keep_alive = tokio::time::interval(KEEP_ALIVE_INTERVAL);
    
    loop {
        tokio::select\! {
            inbound = self.remote_conn.inbound_packet_recv.recv() => {
                // Process message...
                if let Some(msg) = self.process_inbound(payload).await? {
                    return Ok(msg);  // <-- Timer destroyed when function returns\!
                }
            }
            _ = keep_alive.tick() => {
                // Send keep-alive NoOp
                self.noop(vec\![]).await?;
            }
        }
    }
}
```

### The Call Pattern

The `peer_connection_listener` in `p2p_protoc.rs` demonstrates the problematic pattern:

```rust
async fn peer_connection_listener(
    mut conn: PeerConnection,
    // ...
) -> Result<PeerConnectionInbound, TransportError> {
    loop {
        tokio::select\! {
            msg = conn.recv() => {  // Keep-alive timer exists only during this call
                // Return message for processing
                break Ok(PeerConnectionInbound { conn, rx, msg: net_message });
            }
        }
    }
}
```

### Timeline of the Problem

1. `peer_connection_listener` calls `conn.recv()`
2. `recv()` creates keep-alive timer (10 second interval)
3. Message arrives, `recv()` returns it (timer destroyed)
4. `peer_connection_listener` returns the connection and message
5. Upper layer processes message (could take seconds)
6. New `peer_connection_listener` task created
7. Repeat

**Critical Gap**: Between steps 3-6, NO keep-alives are sent because no timer exists\!

## Why This Causes Timeouts

- Keep-alive interval: 10 seconds
- Connection timeout: 30 seconds
- If the gap between `recv()` calls exceeds 30 seconds, connection times out
- Even with shorter gaps, rapid message processing can prevent the timer from ever firing

## Symptoms

1. Connections timeout after 30-60 seconds despite active communication
2. River chat users get stuck in "Subscribing to room..." state
3. Bootstrap never completes (needs 4 stable connections)
4. PUT operations fail due to unstable connections

## Proposed Solution

Keep-alive should run in a separate, persistent task:

```rust
pub struct PeerConnection {
    // ... existing fields ...
    keep_alive_handle: Option<JoinHandle<()>>,
}

impl PeerConnection {
    pub fn start_keep_alive(&mut self) {
        let outbound = self.remote_conn.outbound_packets.clone();
        let remote_addr = self.remote_conn.remote_addr;
        
        self.keep_alive_handle = Some(tokio::spawn(async move {
            let mut interval = tokio::time::interval(KEEP_ALIVE_INTERVAL);
            loop {
                interval.tick().await;
                // Send NoOp through outbound channel
                if outbound.send((remote_addr, noop_packet)).await.is_err() {
                    break; // Connection closed
                }
            }
        }));
    }
}
```

## Benefits of Proposed Solution

1. Keep-alive runs independently of message processing
2. No gaps in keep-alive transmission
3. Connections remain stable even under heavy load
4. Simpler mental model - keep-alive is truly periodic

## Testing

To verify this is the issue:
1. Add logging to track time between `recv()` calls
2. Log when keep-alive timer is created/destroyed
3. Observe that timeouts correlate with gaps > 30 seconds

## Priority

**High** - This is causing production issues with River chat and preventing proper network formation.

## Related Issues

- #1656 - Channel overflow causing packet drops (fixed)
- #1657 - Operation retry system design (addresses symptoms but not this root cause)

### PR DESCRIPTION
**Pull request by sanity**
## Summary

This PR fixes the keep-alive architectural flaw identified in #1658 where connections were timing out after 30 seconds even during active communication.

## Problem

The keep-alive timer was created inside the `PeerConnection::recv()` function and was destroyed every time the function returned. This meant:
- No keep-alives were sent during message processing
- No keep-alives were sent between `recv()` calls
- Connections timed out despite active communication

## Solution

Implemented a persistent keep-alive mechanism:
1. **Persistent Timer**: Keep-alive task spawned in `PeerConnection` constructor
2. **Independent Operation**: Runs in separate tokio task, not tied to `recv()` lifecycle
3. **Continuous NoOps**: Sends NoOp packets every 10 seconds regardless of message processing
4. **Clean Shutdown**: Properly cancelled when connection drops via Drop trait

## Changes

- Added `keep_alive_handle: Option<JoinHandle<()>>` to `PeerConnection`
- Implemented `start_keep_alive()` method to spawn persistent timer task
- Removed old keep-alive timer from `recv()` function
- Added `Drop` implementation to clean up keep-alive task
- Added periodic timeout check in `recv()` (every 5 seconds)

## Testing

- All existing tests pass
- `test_put_with_subscribe_flag` passes (was previously failing)
- Keep-alive now runs continuously even under heavy message load

## Performance Impact

Minimal - one additional tokio task per connection sending a small packet every 10 seconds.

Fixes #1658

### CODE REVIEW

File: crates/core/src/transport/peer_connection.rs [hunk 1]
```diff
@@ -137,7 +147,66 @@ impl PeerConnection {
             failure_count: 0,
             first_failure_time: None,
             last_packet_report_time: Instant::now(),
-        }
+            keep_alive_handle: None,
+        };
+
+        // Start the keep-alive task immediately
+        conn.start_keep_alive();
```
Comment (iduartgomez) [inline crates/core/src/transport/peer_connection.rs]: can't we just start the background task and instance Self with the handle instead of having to mutate self after instancing it just to add the handle?

**Review by iduartgomez — APPROVED** [review]
